name: Sync Production

on: workflow_dispatch

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://blakes24:${{ secrets.ACCESS_TOKEN }}@github.com/blakes24/hflatest-dev2.git"
          source_branch: "main"
          destination_repo: "https://blakes24:${{ secrets.ACCESS_TOKEN }}@github.com/blakes24/hflatest-prod2"
          destination_branch: "main"
