name: Push To Production

on: workflow_dispatch

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "blakes24/hflatest-dev2"
          source_branch: "main"
          destination_repo: "blakes24/hflatest-prod2"
          destination_branch: "main"
